export const globalActionTypes = {
    UPDATE: 'UPDATE',
    UPDATE_TOTAL_ADJUSTED: 'UPDATE_TOTAL_ADJUSTED',
    TOGGLE_MODAL_ADJUST_MARGIN: 'TOGGLE_MODAL_ADJUST_MARGIN',
    TOGGLE_MODAL_CONFIRM_ADJUST: 'TOGGLE_MODAL_CONFIRM_ADJUST',
    TOGGLE_MODAL_SUCCESS_ADJUST: 'TOGGLE_MODAL_SUCCESS_ADJUST',
    TOGGLE_MODAL_RESET: 'TOGGLE_MODAL_RESET',
    UPDATE_AMOUNT: 'UPDATE_AMOUNT',
    RESET_AMOUNT: 'RESET_AMOUNT',
    TOGGLE_MODAL_CANCEL: 'TOGGLE_MODAL_CANCEL'
};
