export const globalActionTypes = {
    UPDATE: 'UPDATE',
    REFETCH: 'REFETCH',
    RESET: 'RESET',
    RESET_AMOUNT: 'RESET_AMOUNT',
    UPDATE_AMOUNT: 'UPDATE_AMOUNT',
    TOGGLE_MODAL_ERROR: 'TOGGLE_MODAL_ERROR',
    TOGGLE_MODAL_RESET: 'TOGGLE_MODAL_RESET',
    TOGGLE_MODAL_CANCEL: 'TOGGLE_MODAL_CANCEL',
    UPDATE_TOTAL_ADJUSTED: 'UPDATE_TOTAL_ADJUSTED',
    TOGGLE_MODAL_ADJUST_MARGIN: 'TOGGLE_MODAL_ADJUST_MARGIN',
    TOGGLE_MODAL_CONFIRM_ADJUST: 'TOGGLE_MODAL_CONFIRM_ADJUST',
    TOGGLE_MODAL_SUCCESS_ADJUST: 'TOGGLE_MODAL_SUCCESS_ADJUST'
};
